name: messagecommunicator # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.4.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: MessageCommunicator is a testing Gui for message-based communication. # 79 char long summary
description: |
  Message Communicator is a testing Gui for message-based communication. It is meant for scenarios 
  when you want to test communication with other devices or software when communication is based on 
  simple readably messages. Message recognition is configurable and supports modes like 
  'Fixes Length' or 'End Symbols'. Currently only TCP is supported but may be expanded in the future 
  by UDP or by Serial Port.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

parts: 
  messagecommunicator:
    plugin: dump
    source: publish/MessageCommunicator-Linux-X64.tar.gz

apps:
  messagecommunicator:
    command: MessageCommunicator-Linux-X64